### ISSUE TITLE
create default functionality of a builder system

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/Builder-System-Plugin#1]

**Comment by kevinxdev** [comment]
@Feier68 https://github.com/gigaclub/Builder-System-Plugin/tree/feature/create-default-functionality-of-a-builder-system-1.16.5-feier68

**Comment by Feier68** [comment]
Commands:
-  builder server create  (welt typ, welt (normal,neheter,end) ,Server name nach auftrag mit nummer )

getrenntes plugin
-fertig mit bau (Discord benachrichtigung)
-invite player   (Discord benachrichtigung)
-remove player    (Discord benachrichtigung)

Configs:
- worldborder grösse (standart)  bearbeitbar  von admins

getrenntes plugin
- ~ max player pro gruppe 
- max welten pro player (vieleicht abhängig von rang)
-
