### ISSUE TITLE
Version Placeholder is not working.

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/Builder-System-Plugin#10]
I think you have to replace this with `%version%`

![2022-03-31_19-22.png](https://images.zenhubusercontent.com/623226cee4e03cb5f7f2dbeb/b33e164c-7bd6-414c-82b3-b7c3e73625c9)

**Comment by Feier68** [comment]
![Unbenannt](https://user-images.githubusercontent.com/25251081/161116259-e221b4eb-ff93-4b38-bfce-c5667a853f38.PNG)
fixt
